package com.example.testingTheory.exceptionTest

fun main() {
    val a : Number = 1
    val b : Double = a as Double
}